site_name: Awesome Video
site_url: https://awesome.video
site_description: A curated list of awesome streaming video tools, frameworks, libraries, and learning resources.
site_author: Nick Krzemienski
repo_name: krzemienski/awesome-video
repo_url: https://github.com/krzemienski/awesome-video
theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: green
  font:
    text: 'Menlo, DejaVu Sans Mono, Consolas, Lucida Console, monospace'
    code: 'Menlo, DejaVu Sans Mono, Consolas, Lucida Console, monospace'
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - search.highlight
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - tables
  - toc:
      permalink: true
plugins:
  - search
  - minify:
      minify_html: true
extra:
  analytics:
    provider: google
    property: G-VQCESB210D
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/krzemienski
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/nkrzemienski
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/krzemienski
extra_css:
    - css/extra.css
nav:
  - "From FFMPEG to playback, streaming video.": "index.md"
